from __future__ import annotations

from urllib.parse import quote_plus


def youtube_search(query: str) -> str:
    return "https://www.youtube.com/results?search_query=" + quote_plus(query)


LEARNING_RESOURCES: tuple[dict[str, str], ...] = (
    {
        "key": "fr-discord-base-docs",
        "language": "fr",
        "type": "docs",
        "category": "Discord",
        "level": "Débutant",
        "title": "Centre d’aide Discord en français",
        "url": "https://support.discord.com/hc/fr",
        "note": "Documentation officielle Discord : compte, serveurs, salons, rôles et sécurité.",
    },
    {
        "key": "fr-discord-base-video",
        "language": "fr",
        "type": "video",
        "category": "Discord",
        "level": "Débutant",
        "title": "Discord : bases complètes en français",
        "url": youtube_search("Discord tutoriel complet français serveur rôles permissions"),
        "note": "Recherche vidéo ciblée pour revoir visuellement les bases Discord.",
    },
    {
        "key": "fr-permissions-video",
        "language": "fr",
        "type": "video",
        "category": "Permissions",
        "level": "Intermédiaire",
        "title": "Permissions et hiérarchie Discord — FR",
        "url": youtube_search("Discord permissions rôles hiérarchie tutoriel français"),
        "note": "Vidéos centrées sur les overwrites, catégories et hiérarchie des rôles.",
    },
    {
        "key": "fr-server-video",
        "language": "fr",
        "type": "video",
        "category": "Serveur",
        "level": "Débutant",
        "title": "Créer un serveur Discord professionnel — FR",
        "url": youtube_search("créer serveur Discord professionnel tutoriel français 2026"),
        "note": "Structure, onboarding, rôles, permissions et organisation d’un serveur.",
    },
    {
        "key": "fr-python-docs",
        "language": "fr",
        "type": "docs",
        "category": "Code",
        "level": "Débutant → avancé",
        "title": "Documentation Python 3 en français",
        "url": "https://docs.python.org/fr/3/",
        "note": "Référence officielle Python pour syntaxe, bibliothèque standard et bonnes pratiques.",
    },
    {
        "key": "fr-python-video",
        "language": "fr",
        "type": "video",
        "category": "Code",
        "level": "Débutant",
        "title": "Python complet pour débuter — FR",
        "url": youtube_search("Python cours complet français débutant"),
        "note": "Recherche vidéo pour apprendre les bases nécessaires avant discord.py.",
    },
    {
        "key": "fr-discordpy-video",
        "language": "fr",
        "type": "video",
        "category": "Bots",
        "level": "Intermédiaire",
        "title": "Créer un bot Discord.py — FR",
        "url": youtube_search("discord.py bot Discord slash commands tutoriel français"),
        "note": "Recherche ciblée : bot Python, slash commands, embeds et événements.",
    },
    {
        "key": "fr-github-docs",
        "language": "fr",
        "type": "docs",
        "category": "Git",
        "level": "Débutant → avancé",
        "title": "Documentation GitHub en français",
        "url": "https://docs.github.com/fr",
        "note": "Documentation officielle GitHub : dépôts, branches, pull requests et Actions.",
    },
    {
        "key": "fr-git-video",
        "language": "fr",
        "type": "video",
        "category": "Git",
        "level": "Débutant",
        "title": "Git & GitHub — FR",
        "url": youtube_search("Git GitHub cours complet français branches pull request"),
        "note": "Recherche vidéo pour le workflow branche → commit → PR → merge.",
    },
    {
        "key": "fr-railway-video",
        "language": "fr",
        "type": "video",
        "category": "Hébergement",
        "level": "Intermédiaire",
        "title": "Déployer un bot sur Railway — FR",
        "url": youtube_search("Railway déployer bot Discord Python français"),
        "note": "Recherche vidéo : variables d’environnement, logs, restart et déploiement.",
    },
    {
        "key": "fr-security-video",
        "language": "fr",
        "type": "video",
        "category": "Sécurité",
        "level": "Intermédiaire",
        "title": "Sécurité d’un serveur Discord — FR",
        "url": youtube_search("sécuriser serveur Discord anti raid permissions français"),
        "note": "Recherche ciblée sur anti-raid, permissions sensibles, webhooks et comptes staff.",
    },
    {
        "key": "fr-sqlite-video",
        "language": "fr",
        "type": "video",
        "category": "Données",
        "level": "Intermédiaire",
        "title": "SQLite avec Python — FR",
        "url": youtube_search("SQLite Python tutoriel français base de données"),
        "note": "Recherche vidéo pour comprendre tables, transactions et accès depuis Python.",
    },
    {
        "key": "en-discord-support",
        "language": "en",
        "type": "docs",
        "category": "Discord",
        "level": "Beginner",
        "title": "Discord Help Center",
        "url": "https://support.discord.com/hc/en-us",
        "note": "Official Discord documentation for accounts, servers, roles, channels and safety.",
    },
    {
        "key": "en-discord-video",
        "language": "en",
        "type": "video",
        "category": "Discord",
        "level": "Beginner",
        "title": "Discord server setup — EN",
        "url": youtube_search("Discord server setup roles permissions tutorial English"),
        "note": "Video search focused on clean server structure, roles and permissions.",
    },
    {
        "key": "en-developer-docs",
        "language": "en",
        "type": "docs",
        "category": "Bots",
        "level": "Intermediate",
        "title": "Discord Developer Documentation",
        "url": "https://discord.com/developers/docs/intro",
        "note": "Official reference for applications, interactions, intents, permissions and API behavior.",
    },
    {
        "key": "en-discordpy-docs",
        "language": "en",
        "type": "docs",
        "category": "Bots",
        "level": "Intermediate",
        "title": "discord.py documentation",
        "url": "https://discordpy.readthedocs.io/en/stable/",
        "note": "Primary framework documentation for commands, interactions, events and API objects.",
    },
    {
        "key": "en-discordpy-video",
        "language": "en",
        "type": "video",
        "category": "Bots",
        "level": "Intermediate",
        "title": "discord.py slash commands — EN",
        "url": youtube_search("discord.py slash commands interactions tutorial English"),
        "note": "Video search for modern discord.py application commands and interaction patterns.",
    },
    {
        "key": "en-python-docs",
        "language": "en",
        "type": "docs",
        "category": "Code",
        "level": "Beginner → advanced",
        "title": "Python 3 documentation",
        "url": "https://docs.python.org/3/",
        "note": "Official Python language and standard library reference.",
    },
    {
        "key": "en-github-docs",
        "language": "en",
        "type": "docs",
        "category": "Git",
        "level": "Beginner → advanced",
        "title": "GitHub Docs",
        "url": "https://docs.github.com/en",
        "note": "Official GitHub reference for repositories, pull requests, Actions and security.",
    },
    {
        "key": "en-git-video",
        "language": "en",
        "type": "video",
        "category": "Git",
        "level": "Beginner",
        "title": "Git & GitHub workflow — EN",
        "url": youtube_search("Git GitHub branches pull requests tutorial English"),
        "note": "Video search for professional branch, review and merge workflows.",
    },
    {
        "key": "en-railway-docs",
        "language": "en",
        "type": "docs",
        "category": "Hosting",
        "level": "Intermediate",
        "title": "Railway Docs",
        "url": "https://docs.railway.com/",
        "note": "Official Railway documentation for services, variables, volumes, logs and deployments.",
    },
    {
        "key": "en-railway-video",
        "language": "en",
        "type": "video",
        "category": "Hosting",
        "level": "Intermediate",
        "title": "Deploy Python bot on Railway — EN",
        "url": youtube_search("Railway deploy Python Discord bot tutorial English"),
        "note": "Video search for environment variables, persistence and production deployment.",
    },
    {
        "key": "en-security-video",
        "language": "en",
        "type": "video",
        "category": "Security",
        "level": "Intermediate",
        "title": "Discord server security — EN",
        "url": youtube_search("Discord server security permissions anti raid tutorial English"),
        "note": "Video search for least privilege, anti-raid, bot permissions and incident response.",
    },
    {
        "key": "en-sqlite-docs",
        "language": "en",
        "type": "docs",
        "category": "Data",
        "level": "Intermediate",
        "title": "SQLite documentation",
        "url": "https://www.sqlite.org/docs.html",
        "note": "Official SQLite documentation for transactions, locking, SQL and persistence.",
    },
)


CHALLENGE_LIBRARY: dict[str, dict[str, object]] = {
    "discord-1": {
        "title": "Onboarding en 60 secondes",
        "category": "Discord",
        "difficulty": "Débutant",
        "description": "Conçois une arrivée où un nouveau membre comprend le serveur et sa prochaine action en moins d’une minute.",
        "criteria": ("Un message d’accueil court", "Les règles sont accessibles", "Une action suivante unique est évidente"),
        "reward": 35,
        "estimated": "15–25 min",
    },
    "discord-2": {
        "title": "Navigation sans confusion",
        "category": "Discord",
        "difficulty": "Débutant",
        "description": "Réorganise un serveur test pour que chaque salon permanent ait une mission différente.",
        "criteria": ("Aucun salon dupliqué", "Noms compréhensibles", "Chaque catégorie a une logique claire"),
        "reward": 45,
        "estimated": "20–30 min",
    },
    "serveur-1": {
        "title": "Serveur compact",
        "category": "Serveur",
        "difficulty": "Débutant",
        "description": "Construis un serveur test compact et explique l’utilité de chaque salon.",
        "criteria": ("15 salons permanents maximum", "Chaque salon a une mission", "Aucun salon vide juste pour décorer"),
        "reward": 40,
        "estimated": "25–40 min",
    },
    "serveur-2": {
        "title": "Architecture entreprise",
        "category": "Serveur",
        "difficulty": "Intermédiaire",
        "description": "Conçois la structure d’un serveur qui vend un service, forme ses membres et garde un espace staff privé.",
        "criteria": ("Onboarding séparé du support", "Formation séparée des opérations staff", "Permissions cohérentes par catégorie"),
        "reward": 70,
        "estimated": "40–60 min",
    },
    "permissions-1": {
        "title": "Permissions propres",
        "category": "Permissions",
        "difficulty": "Débutant",
        "description": "Crée Membre, Modérateur et Administrateur sans donner Administrateur au rôle Modérateur, puis configure un salon staff privé.",
        "criteria": ("Modérateur sans Administrateur", "Salon staff invisible aux membres", "Hiérarchie logique"),
        "reward": 50,
        "estimated": "20–35 min",
    },
    "permissions-2": {
        "title": "Overwrites maîtrisés",
        "category": "Permissions",
        "difficulty": "Intermédiaire",
        "description": "Crée une catégorie privée avec une exception contrôlée sur un seul salon.",
        "criteria": ("Base de catégorie correcte", "Une seule exception nécessaire", "Test avec un rôle membre"),
        "reward": 65,
        "estimated": "25–40 min",
    },
    "permissions-3": {
        "title": "Audit moindre privilège",
        "category": "Permissions",
        "difficulty": "Avancé",
        "description": "Analyse tous les rôles sensibles d’un serveur test et réduis les droits inutiles sans casser les missions du staff.",
        "criteria": ("Inventaire des permissions sensibles", "Justification de chaque permission conservée", "Plan de test après correction"),
        "reward": 100,
        "estimated": "45–75 min",
    },
    "security-1": {
        "title": "Audit sécurité",
        "category": "Sécurité",
        "difficulty": "Intermédiaire",
        "description": "Relève au moins cinq risques de permissions ou d’organisation puis propose une correction pour chacun.",
        "criteria": ("5 risques minimum", "Une correction par risque", "Priorité critique/importante/confort"),
        "reward": 90,
        "estimated": "35–60 min",
    },
    "security-2": {
        "title": "Plan anti-raid",
        "category": "Sécurité",
        "difficulty": "Intermédiaire",
        "description": "Écris un plan d’urgence utilisable par le staff pendant un raid sans donner des permissions excessives.",
        "criteria": ("Détection", "Actions immédiates", "Retour à la normale et journalisation"),
        "reward": 85,
        "estimated": "30–50 min",
    },
    "security-3": {
        "title": "Incident secret exposé",
        "category": "Sécurité",
        "difficulty": "Avancé",
        "description": "Prépare une procédure défensive pour un token ou une clé API exposée.",
        "criteria": ("Révocation/régénération immédiate", "Recherche de l’exposition sans recopier le secret", "Rotation et vérification des accès"),
        "reward": 110,
        "estimated": "30–45 min",
    },
    "helper-1": {
        "title": "Aider sans faire à la place",
        "category": "Support",
        "difficulty": "Débutant",
        "description": "Prends un problème Discord fictif, écris un diagnostic puis une réponse en étapes permettant au membre de refaire seul.",
        "criteria": ("Diagnostic clair", "3 à 5 étapes maximum", "Explication du pourquoi"),
        "reward": 50,
        "estimated": "15–25 min",
    },
    "helper-2": {
        "title": "Escalade support propre",
        "category": "Support",
        "difficulty": "Intermédiaire",
        "description": "Décide quand une question reste publique et quand elle doit devenir un ticket privé.",
        "criteria": ("Règles de décision explicites", "Secrets jamais demandés", "Contexte transmis sans duplication"),
        "reward": 65,
        "estimated": "20–30 min",
    },
    "mentor-1": {
        "title": "Mini-session de mentorat",
        "category": "Support",
        "difficulty": "Intermédiaire",
        "description": "Prépare une session de 20 minutes avec objectif, exercice et vérification finale.",
        "criteria": ("Objectif mesurable", "Exercice pratique", "Critère de réussite final"),
        "reward": 75,
        "estimated": "25–35 min",
    },
    "bot-1": {
        "title": "Premier bot slash",
        "category": "Bots",
        "difficulty": "Intermédiaire",
        "description": "Crée un bot avec /ping et /userinfo, sans token dans le code, avec une gestion d’erreur simple.",
        "criteria": ("Token via variable d’environnement", "Deux commandes slash", "Erreur utilisateur propre"),
        "reward": 80,
        "estimated": "45–90 min",
    },
    "bot-2": {
        "title": "Bot panel-first",
        "category": "Bots",
        "difficulty": "Intermédiaire",
        "description": "Crée une fonctionnalité avec embed, select et modal plutôt qu’une multiplication de commandes slash.",
        "criteria": ("Une intention claire par action", "Réponses privées quand nécessaire", "Aucun bouton dupliqué"),
        "reward": 95,
        "estimated": "60–100 min",
    },
    "bot-3": {
        "title": "Permissions fail-closed",
        "category": "Bots",
        "difficulty": "Avancé",
        "description": "Ajoute une action sensible qui refuse l’accès si la permission n’est pas explicitement accordée.",
        "criteria": ("Contrôle avant mutation", "Erreur claire", "Test autorisé + refusé"),
        "reward": 120,
        "estimated": "60–90 min",
    },
    "code-1": {
        "title": "Traceback → correction",
        "category": "Code",
        "difficulty": "Débutant",
        "description": "Pars d’un traceback Python, identifie la cause et écris un test qui reproduit le bug avant la correction.",
        "criteria": ("Cause identifiée", "Reproduction minimale", "Test passant après correction"),
        "reward": 70,
        "estimated": "30–50 min",
    },
    "code-2": {
        "title": "Refactor sans régression",
        "category": "Code",
        "difficulty": "Avancé",
        "description": "Découpe une fonction trop longue sans modifier son comportement observable.",
        "criteria": ("Responsabilités séparées", "Tests avant/après", "Aucune régression visible"),
        "reward": 115,
        "estimated": "60–120 min",
    },
    "git-1": {
        "title": "Workflow branche + PR",
        "category": "Git",
        "difficulty": "Débutant",
        "description": "Fais une modification sur une branche, vérifie le diff puis ouvre une PR propre sans pousser directement sur main.",
        "criteria": ("Branche dédiée", "Commit lisible", "PR avec résumé et tests"),
        "reward": 60,
        "estimated": "20–35 min",
    },
    "git-2": {
        "title": "Conflit Git maîtrisé",
        "category": "Git",
        "difficulty": "Intermédiaire",
        "description": "Résous un conflit de merge volontaire sans utiliser force-push sur main.",
        "criteria": ("Conflit compris", "Résolution fichier par fichier", "Historique final cohérent"),
        "reward": 85,
        "estimated": "30–50 min",
    },
    "hosting-1": {
        "title": "Déploiement Railway propre",
        "category": "Hébergement",
        "difficulty": "Intermédiaire",
        "description": "Prépare un déploiement avec variables, start command, logs et vérification après mise en ligne.",
        "criteria": ("Secrets hors du dépôt", "Commande de démarrage correcte", "Logs vérifiés après déploiement"),
        "reward": 90,
        "estimated": "35–60 min",
    },
    "hosting-2": {
        "title": "Persistance après restart",
        "category": "Hébergement",
        "difficulty": "Avancé",
        "description": "Configure une base ou un fichier pour qu’il survive aux redémarrages d’un service Railway.",
        "criteria": ("Volume monté", "Chemin de données dans le volume", "Test restart sans perte"),
        "reward": 115,
        "estimated": "45–75 min",
    },
    "data-1": {
        "title": "SQLite sans lock surprise",
        "category": "Données",
        "difficulty": "Avancé",
        "description": "Conçois un flux d’écriture SQLite qui évite les doubles validations et les écritures concurrentes incohérentes.",
        "criteria": ("Transaction explicite", "Écriture idempotente", "Test concurrence ou double clic"),
        "reward": 125,
        "estimated": "60–100 min",
    },
    "enterprise-1": {
        "title": "Audit expérience entreprise",
        "category": "Entreprise",
        "difficulty": "Avancé",
        "description": "Évalue un serveur comme un produit : onboarding, support, formation, sécurité, image et opérations staff.",
        "criteria": ("Score par domaine", "3 priorités à fort impact", "Plan d’amélioration mesurable"),
        "reward": 130,
        "estimated": "60–90 min",
    },
}


CERTIFICATIONS: dict[str, dict[str, object]] = {
    "discord-foundations": {
        "title": "Discord Foundations",
        "level": "Foundation",
        "description": "Comprendre Discord, l’onboarding et une structure de serveur claire.",
        "challenges": ("discord-1", "discord-2", "serveur-1", "permissions-1"),
    },
    "server-operations": {
        "title": "Server Operations",
        "level": "Professional",
        "description": "Construire et exploiter un serveur avec support, staff et permissions cohérentes.",
        "challenges": ("serveur-2", "permissions-2", "helper-2", "mentor-1", "enterprise-1"),
    },
    "security-specialist": {
        "title": "Security Specialist",
        "level": "Professional",
        "description": "Maîtriser le moindre privilège, l’audit, l’anti-raid et les procédures d’incident.",
        "challenges": ("permissions-3", "security-1", "security-2", "security-3"),
    },
    "bot-engineering": {
        "title": "Bot Engineering",
        "level": "Professional",
        "description": "Développer, tester et déployer un bot Discord maintenable et sûr.",
        "challenges": ("bot-1", "bot-2", "bot-3", "code-1", "git-1", "hosting-1"),
    },
    "bot-engineering-advanced": {
        "title": "Bot Engineering Advanced",
        "level": "Advanced",
        "description": "Refactor, concurrence, persistance et opérations de production.",
        "challenges": ("code-2", "git-2", "hosting-2", "data-1"),
    },
}


def resources_for(language: str) -> tuple[dict[str, str], ...]:
    language = language.casefold().strip()
    return tuple(item for item in LEARNING_RESOURCES if item["language"] == language)


def challenge_categories() -> tuple[str, ...]:
    return tuple(sorted({str(item["category"]) for item in CHALLENGE_LIBRARY.values()}))


def challenges_for_category(category: str) -> tuple[tuple[str, dict[str, object]], ...]:
    return tuple((key, item) for key, item in CHALLENGE_LIBRARY.items() if item["category"] == category)
