"""Machine-readable V54 capability manifest.

This file intentionally lists concrete shipped capabilities, not roadmap items.
It is used by tests/documentation to keep the product surface honest.
"""

V54_CAPABILITIES = (
    "help.home.category-routing",
    "help.home.free-text-routing",
    "help.quick.symptom-select",
    "help.quick.private-results",
    "help.guides.category-library",
    "help.guides.topic-drilldown",
    "help.permissions.channel-visibility",
    "help.permissions.send-messages",
    "help.permissions.role-hierarchy",
    "help.permissions.category-inheritance",
    "help.bots.offline-diagnostic",
    "help.bots.command-sync-diagnostic",
    "help.bots.permission-diagnostic",
    "help.bots.intents-diagnostic",
    "help.hosting.railway-restart",
    "help.hosting.persistent-volume",
    "help.hosting.environment-variables",
    "help.code.python-traceback",
    "help.code.dependencies",
    "help.code.sqlite-locking",
    "help.code.git-conflicts",
    "help.tickets.open-failure",
    "help.tickets.duplicate-detection-guidance",
    "help.server.onboarding",
    "help.server.channel-clutter",
    "help.security.raid-response",
    "help.security.secret-leak",
    "help.security.suspicious-bot",
    "help.security.webhook-abuse",
    "help.discord.notifications",
    "help.discord.stale-client-state",
    "help.escalation.prefilled-diagnostic-context",
    "help.escalation.active-ticket-deduplication",
    "help.ai.contextual-handoff",
    "help.channels.auto-create",
    "help.channels.auto-permissions",
    "help.panels.auto-reconcile",
    "help.legacy-center-runtime-redirect",
    "ux.no-owner-dashboard-runtime",
    "ux.no-ops-dashboard-runtime",
    "ux.only-setup-and-buy-public-slash",
)
